# Generated by Django 5.0.1 on 2024-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="isSent",
            field=models.BooleanField(default=True),
        ),
    ]
