# Generated by Django 5.0.1 on 2024-03-20 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_issent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="isSent",
        ),
    ]
