# Generated by Django 5.0.1 on 2024-03-26 18:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_rename_sendername_blockuser_own_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockuser",
            name="blocked_players",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
