# Generated by Django 5.0.1 on 2024-03-26 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_blockuser_blocked_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockuser",
            name="blocked_users",
        ),
    ]
