# Generated by Django 5.0.1 on 2024-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_rename_blocked_players_blockuser_blocked_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="notification",
            field=models.BooleanField(default=False),
        ),
    ]
