# Generated by Django 5.0.1 on 2024-04-30 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_userlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="recipient",
        ),
    ]
