# Generated by Django 5.0.1 on 2024-06-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_usernotifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernotifications",
            options={"ordering": ["-created"]},
        ),
    ]
