# Generated by Django 5.0.1 on 2024-01-21 03:34

import django.db.models.deletion
import gameplay.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_type", models.CharField(default="pong", max_length=100)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("is_winner", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("session_id", models.UUIDField(default=uuid.uuid4)),
                ("player_number", models.IntegerField(default=1)),
                (
                    "player",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_started", models.BooleanField(default=False)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "game_code",
                    models.CharField(
                        default=gameplay.models.generate_game_code, max_length=10
                    ),
                ),
                ("game_type", models.CharField(default="pong", max_length=100)),
                ("level", models.IntegerField(default=1)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("max_players", models.IntegerField(blank=True, default=2)),
                (
                    "players",
                    models.ManyToManyField(
                        through="gameplay.GamePlayer", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gameplay.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="game_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gameplay.gameroom"
            ),
        ),
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameplay.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(
                through="gameplay.TournamentPlayer", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.UniqueConstraint(
                fields=("game_room", "player"), name="Players in room"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.UniqueConstraint(
                fields=("game_room", "player_number"),
                name="Player number unique in room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameroom",
            unique_together={("game_code", "is_active")},
        ),
    ]
