# Generated by Django 5.0.1 on 2024-01-05 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
