# Generated by Django 5.0.1 on 2024-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="loss",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="win",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
