# Generated by Django 5.0.1 on 2024-01-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0002_gameroom_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="player1_session_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="player2_session_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="gameroom",
            name="player1_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="gameroom",
            name="player2_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
