# Generated by Django 5.0.1 on 2024-04-23 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0002_gameplayer_loss_gameplayer_win"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplayer",
            name="loss",
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="win",
        ),
    ]
