# Generated by Django 5.0.1 on 2024-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0002_playerusermap"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerusermap",
            name="consumer_name",
            field=models.TextField(null=True),
        ),
    ]
