# Generated by Django 5.0.1 on 2024-01-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0003_gameroom_player1_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
