# Generated by Django 5.0.1 on 2024-05-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0005_tournament_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentplayer",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
