# Generated by Django 5.0.1 on 2024-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0007_alter_tournamentplayer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentplayer",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
    ]
