# Generated by Django 5.0.1 on 2024-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0008_tournamentplayer_is_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
